# vim:ft=kitty

## name:     Tokyo Night Moon
## author:   Enki
## license:  MIT
## blurb:    A clean, dark Kitty theme that celebrates the lights of Tokyo at night.

# The basic colors
foreground              #c0caf5
background              #222436
selection_foreground    #c0caf5
selection_background    #2d3f76

# Cursor colors
cursor                  #c0caf5
cursor_text_color       #222436

# Scrollbar colors
scrollbar_handle_color  #444a73
scrollbar_track_color   #1e2030

# URL color when hovering with mouse
url_color               #73daca

# Kitty window border colors
active_border_color     #82aaff
inactive_border_color   #2f334d
bell_border_color       #e0af68

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #1e2030
active_tab_background   #82aaff
inactive_tab_foreground #545c7e
inactive_tab_background #222436
tab_bar_background      #1b1d2b

# Colors for marks
mark1_foreground #1e2030
mark1_background #c0caf5
mark2_foreground #1e2030
mark2_background #a9b1d6
mark3_foreground #1e2030
mark3_background #444a73

# The 16 terminal colors

# black
color0 #1b1d2b
color8 #444a73

# red
color1 #ff757f
color9 #ff757f

# green
color2  #c3e88d
color10 #c3e88d

# yellow
color3  #ffc777
color11 #ffc777

# blue
color4  #82aaff
color12 #82aaff

# magenta
color5  #c099ff
color13 #c099ff

# cyan
color6  #86e1fc
color14 #86e1fc

# white
color7  #828bb8
color15 #c8d3f5