#!/bin/sh
cd ~
# user preferred settings

#cursor size
export XCURSOR_SIZE=24
export HYPRCURSOR_THEME=Sweet-cursors
export XCURSOR_THEME=Sweet-cursors

# text editor
export MICRO_TRUECOLOR=1
export EDITOR=/usr/bin/micro

#browser
export BROWSER=firedragon
#terminal
export TERM=foot
#mail
export MAIL=thunderbird

# check /usr/local/bin/hyprstart 
