preload = /usr/share/wallpapers/hollow/*
wallpaper = ,/usr/share/wallpapers/hollow/hollow-knight.jpg

wallpaper {
  monitor = eDP-1
  path = /usr/share/wallpapers/hollow/hollow-knight.jpg
  fit_mode = cover
}
wallpaper {
  monitor = DP-1
  path = /usr/share/wallpapers/meowrch/3.png
  fit_mode = cover
}
wallpaper {
  monitor = HDMI-A-1
  path = /usr/share/wallpapers/meowrch/4.png
  fit_mode = cover
}
splash = false
ipc = false
